### ISSUE TITLE
[Help needed] Port forwarding doesn't working – what i'm missing?

### ISSUE THREAD

**Issue by tinpansoul** [mblaschke/vagrant-development#104]
Hello. I'm using `ubuntu-16.04` branch with minimal changes in `vm.yml` (trimmed):

```yml
  network:
    # Private/Host-only network
    private:
      address: 192.168.56.2
      netmask: 192.168.56.0/24
  portForwarding:
    - { guest: 80, host: 8000, hostIp: '0.0.0.0', protocol: 'tcp' }
    - { guest: 13306, host: 3306, hostIp: '0.0.0.0', protocol: 'tcp' }
FIREWALL:
  rules:
      - { port: 80, protocol: tcp }  # HTTP
      - { port: 8000, protocol: tcp }  # HTTP
      - { port: 443, protocol: tcp } # HTTPS
```

Inside OSX and Ubuntu `/etc/hosts` contains this line: `127.0.0.1  api.example.vm`

Server is configured correctly – trying to send request _from_inside_ is okay (testing with `http api.example.vm:80`).

But from OSX requests do not go trough (testing with `http api.example.vm:8000`).

What i'm missing in configuration? OSX Firewall is turned off, no proxy. How to debug this?

ps: OSX Sierra.

**Comment by mblaschke** [comment]
What are you binding to port 80 on this VM? a docker image?
Is it working if you run`sudo nc -l 80` and then access `http://localhost:8000` on osx? Do you see the HTTP haeder in the terminal?

**Comment by tinpansoul** [comment]
I want to forward 8000 port from osx to 80 port in vagrant image in ubuntu. Server inside vagrant vm just listening 80 port without any docker or so.

### Inside vagrant:

```
vagrant@DEV-VM ~ % sudo nc -l 80
nc: Address already in use

vagrant@DEV-VM ~ % sudo lsof -Pni4 | grep LISTEN | grep 80
nginx     1720     root   10u  IPv4  19344      0t0  TCP 127.0.0.1:80 (LISTEN)
nginx     1720     root   11u  IPv4  19345      0t0  TCP 127.0.0.1:8080 (LISTEN)
nginx     1722 www-data   10u  IPv4  19344      0t0  TCP 127.0.0.1:80 (LISTEN)
nginx     1722 www-data   11u  IPv4  19345      0t0  TCP 127.0.0.1:8080 (LISTEN)
nginx     1723 www-data   10u  IPv4  19344      0t0  TCP 127.0.0.1:80 (LISTEN)
nginx     1723 www-data   11u  IPv4  19345      0t0  TCP 127.0.0.1:8080 (LISTEN)
```

### Inside osx:

```
macboo@trogwar ~ sudo lsof -Pni4 | grep LISTEN | grep 80
VBoxHeadl 10412        trogwar   16u  IPv4 0xc21398b1399dacf      0t0  TCP *:8000 (LISTEN)
VBoxHeadl 10412        trogwar   17u  IPv4 0xc21398b0124e3c7      0t0  TCP 127.0.0.1:8000 (LISTEN)

macboo@trogwar ~ sudo nc -l 8000
nc: Address already in use

macboo@trogwar ~ curl -IL localhost:8000
curl: (7) Failed to connect to localhost port 8000: Operation timed out

macboo@trogwar ~ cat /etc/hosts | grep vm
127.0.0.1	api.example.vm
127.0.0.1	example.vm

macboo@trogwar ~ curl -IL api.example.vm:8000
curl: (7) Failed to connect to api.example.vm port 8000: Operation timed out
```

**Comment by mblaschke** [comment]
What docker containers are running? is dory (reverse proxy) running on vagrant vm?
check `docker ps`

**Comment by tinpansoul** [comment]
No docker containers are running, just don't use them right now – docker is not even installed (on both systems).

`vm.yml`:
```yaml
###################
# Provisioning features
###################
PROVISION:
  update:      1      # do full system update for each full provisoning
  samba:       1      # Samba server
  ntp:         1      # Time synchronization
  mail:        1      # Mail sandbox
  php:         1      # Local PHP
  docker:      0      # Docker server
  dockerDory:  0      # Docker docker service --> https://github.com/FreedomBen/dory
  clitools:    0      # CliTools
  dnsmasq:     0      # dnsmasq service (needed for docker consul registration)
  consul:      0      # Docker consul service
  desktop:     0      # GUI desktop [0, kde, unity, gnome]
  manpages:    1      # Manpages are not available in baseimage, so reinstall them
  buildEssentials: 0  # build essentials (gcc, compilers...)

  ## Development domain (automatic redirect of *.docker for internal use)
  developmentDomain: 'vm'
```

So, `docker ps` gives error "command not found: docker" on both systems.
